'use client';

import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {speakKorean,stopKoreanSpeech} from './korean-speech';
import './hanbok-studio.css';

type Props={home:()=>void;soundOn:boolean;toggleSound:()=>void};
type Mode='start'|'design'|'names';
type NameMode='explore'|'cards'|'labels';
type GarmentName='저고리'|'치마'|'바지'|'두루마기'|'버선'|'꽃신'|'노리개';
type Slot='socks'|'bottom'|'top'|'coat'|'shoes'|'ornament';
type Pattern='무늬 없음'|'꽃무늬'|'구름무늬'|'나비무늬'|'단순 반복무늬';
type Garment={id:string;name:GarmentName;slot:Slot;img:string;color:string;variant:string};
type Worn={garment:Garment;color:string;pattern:Pattern};
type Outfit=Partial<Record<Slot,Worn>>;

const root='/hanbok-studio/garments/';
const names:GarmentName[]=['저고리','치마','바지','두루마기','버선','꽃신','노리개'];
const messages:Record<GarmentName,string>={저고리:'저고리예요.',치마:'치마예요.',바지:'바지예요.',두루마기:'두루마기예요.',버선:'버선이에요.',꽃신:'꽃신이에요.',노리개:'노리개예요.'};
const hints:Record<GarmentName,string>={저고리:'몸의 위쪽에 입는 옷이에요.',치마:'아래로 넓게 펼쳐진 옷이에요.',바지:'두 다리를 넣어 입는 옷이에요.',두루마기:'한복 위에 입는 긴 옷이에요.',버선:'발에 먼저 신는 흰색 옷이에요.',꽃신:'버선 위에 신어요.',노리개:'한복에 다는 장식이에요.'};
const categories:GarmentName[]=names;
const colors=[['빨강','#e7473c'],['분홍','#ed8eaa'],['노랑','#f2bd37'],['초록','#318b61'],['파랑','#3789c4'],['남색','#34527d'],['보라','#78569d'],['흰색','#fffaf0'],['연두','#91c86c'],['하늘색','#91cbe4']];
const patterns:Pattern[]=['무늬 없음','꽃무늬','구름무늬','나비무늬','단순 반복무늬'];
const slotOrder:Slot[]=['socks','bottom','top','coat','shoes','ornament'];
const make=(name:GarmentName,count:number,slot:Slot,file:string,palette:string[],available=99)=>Array.from({length:count},(_,index):Garment=>({id:`${file}-${index+1}`,name,slot,img:`${root}${file}-${index%available+1}.png`,color:palette[index%palette.length],variant:`${name} ${index+1}`}));
const garments:Garment[]=[
  ...make('저고리',6,'top','jeogori',['#e7473c','#ed8eaa','#f2bd37','#318b61','#3789c4','#78569d'],6).map((garment,index)=>index===2?{...garment,img:`${root}jeogori-boy-v1.png`,variant:'남자 저고리'}:garment),
  ...make('치마',5,'bottom','chima',['#e7473c','#ed8eaa','#f2bd37','#318b61','#3789c4'],5),
  ...make('바지',5,'bottom','baji',['#34527d','#d9c39f','#91c86c','#78569d','#91cbe4'],5),
  ...make('두루마기',3,'coat','durumagi',['#496aa3','#c98286','#c9b68d'],3).map((garment,index)=>index===0?{...garment,img:`${root}durumagi-complete-v2.png`}:garment),
  ...make('버선',3,'socks','beoseon',['#fffaf0','#e9e6dc','#f5e6cf'],2).map((garment,index)=>({...garment,img:`${root}beoseon-${index%2+1}-aligned.png`})),
  ...make('꽃신',4,'shoes','flower-shoes',['#d83f44','#315f8b','#ed8eaa','#78569d'],2).map((garment,index)=>({...garment,img:`${root}flower-shoes-${index%2+1}-aligned.png`})),
  ...Array.from({length:4},(_,index):Garment=>({id:`norigae-${index+1}`,name:'노리개',slot:'ornament',img:`${root}norigae.png`,color:['#e6ad28','#e7473c','#318b61','#3789c4'][index],variant:`노리개 ${index+1}`})),
];
const boyJeogori:Garment={id:'jeogori-boy-v1',name:'저고리',slot:'top',img:`${root}jeogori-boy-v1.png`,color:'#d9c39f',variant:'남자 저고리'};
const findGarment=(name:GarmentName,number=1)=>garments.find(value=>value.name===name&&value.id.endsWith(`-${number}`))||garments.find(value=>value.name===name)!;
const makeWorn=(name:GarmentName,number=1):Worn=>{const garment=findGarment(name,number);return{garment,color:garment.color,pattern:'무늬 없음'}};
const girlOutfit:Outfit={socks:makeWorn('버선'),bottom:makeWorn('치마',2),top:makeWorn('저고리',1),shoes:makeWorn('꽃신'),ornament:makeWorn('노리개')};
const boyOutfit:Outfit={socks:makeWorn('버선',2),bottom:makeWorn('바지',2),top:{garment:boyJeogori,color:boyJeogori.color,pattern:'무늬 없음'},shoes:makeWorn('꽃신',2)};

function playCorrectSound(soundOn:boolean){
  if(!soundOn||typeof window==='undefined')return;
  const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;
  if(!AudioContextClass)return;
  const context=new AudioContextClass();
  const now=context.currentTime;
  [659.25,783.99,987.77].forEach((frequency,index)=>{
    const oscillator=context.createOscillator();
    const gain=context.createGain();
    oscillator.type='sine';oscillator.frequency.value=frequency;
    gain.gain.setValueAtTime(0,now+index*.11);
    gain.gain.linearRampToValueAtTime(.16,now+index*.11+.015);
    gain.gain.exponentialRampToValueAtTime(.001,now+index*.11+.28);
    oscillator.connect(gain);gain.connect(context.destination);
    oscillator.start(now+index*.11);oscillator.stop(now+index*.11+.3);
  });
  window.setTimeout(()=>void context.close(),800);
}

function Header({title,back,home,soundOn,toggleSound}:{title:string;back:()=>void;home:()=>void;soundOn:boolean;toggleSound:()=>void}){return <header className="hb-header"><Button variant="outline" onClick={home}>처음으로</Button><Button variant="outline" onClick={back}>← 이전</Button><h1>{title}</h1><Button variant="outline" onClick={toggleSound}>{soundOn?'소리 켬':'소리 끔'}</Button></header>}
function Layer({slot,worn,selected,onSelect,side}:{slot:Slot;worn:Worn;selected:boolean;onSelect:()=>void;side?:'girl'|'boy'}){const style={'--tint':worn.color,'--mask':`url(${worn.garment.img})`} as React.CSSProperties;return <button type="button" data-hb-side={side} data-hb-slot={slot} className={`hb-layer slot-${slot} pattern-${patterns.indexOf(worn.pattern)} ${selected?'selected':''}`} style={style} onClick={event=>{event.stopPropagation();onSelect()}} aria-label={`${worn.garment.name} 전체`}><img src={worn.garment.img} alt="" draggable={false}/><i className="hb-tint"/><i className="hb-pattern"/></button>}
function Character({kind,outfit,selected,onSelect,labels,side}:{kind:0|1;outfit:Outfit;selected?:Slot|null;onSelect?:(slot:Slot)=>void;labels?:Partial<Record<Slot,string>>;side?:'girl'|'boy'}){return <div className="hb-character"><img className="hb-base" src={`/hanbok-studio/base/child-${kind?'b':'a'}.png`} alt="흰색 런닝셔츠와 사각 반바지를 입고 정면으로 선 어린이" draggable={false}/>{slotOrder.map(slot=>outfit[slot]&&<Layer key={slot} slot={slot} worn={outfit[slot]!} selected={selected===slot} onSelect={()=>onSelect?.(slot)} side={side}/>)}{Object.entries(labels||{}).map(([slot,label])=><span key={slot} className={`hb-fixed-name label-${slot}`}>{label}</span>)}</div>}

function Design({soundOn,onNames,home}:{soundOn:boolean;onNames:()=>void;home:()=>void}){
  const [category,setCategory]=useState<GarmentName>('저고리');const [kind,setKind]=useState<0|1>(0);const [outfit,setOutfit]=useState<Outfit>({});const [selected,setSelected]=useState<Slot|null>(null);const [pending,setPending]=useState<Garment|null>(null);const [message,setMessage]=useState('옷을 끌어 캐릭터에게 입혀 보세요.');const [drag,setDrag]=useState<{garment:Garment;x:number;y:number}|null>(null);const [finished,setFinished]=useState(false);const stage=useRef<HTMLDivElement>(null);const start=useRef({x:0,y:0});const moved=useRef(false);
  const equip=(garment:Garment)=>{setOutfit(value=>({...value,[garment.slot]:{garment,color:garment.color,pattern:'무늬 없음'}}));setSelected(garment.slot);setPending(null);setMessage(messages[garment.name]);speakKorean(messages[garment.name],soundOn)};
  const down=(garment:Garment,event:React.PointerEvent)=>{event.currentTarget.setPointerCapture(event.pointerId);start.current={x:event.clientX,y:event.clientY};moved.current=false;setDrag({garment,x:event.clientX,y:event.clientY-78});event.preventDefault()};
  const move=(event:React.PointerEvent)=>{if(!drag)return;if(Math.hypot(event.clientX-start.current.x,event.clientY-start.current.y)>8)moved.current=true;setDrag({...drag,x:event.clientX,y:event.clientY-78})};
  const up=(event:React.PointerEvent)=>{if(!drag)return;const rect=stage.current?.getBoundingClientRect();if(moved.current&&rect&&event.clientX>=rect.left-20&&event.clientX<=rect.right+20&&event.clientY>=rect.top-20&&event.clientY<=rect.bottom+20)equip(drag.garment);else{setPending(drag.garment);setMessage(`${drag.garment.name} 선택! 캐릭터를 누르면 입어요.`);speakKorean(messages[drag.garment.name],soundOn)}setDrag(null)};
  const selectLayer=(slot:Slot)=>{if(pending)return;setSelected(slot);const worn=outfit[slot];if(worn){setMessage(messages[worn.garment.name]);speakKorean(messages[worn.garment.name],soundOn)}};
  const change=(patch:Partial<Worn>)=>selected&&setOutfit(value=>value[selected]?({...value,[selected]:{...value[selected]!,...patch}}):value);
  const finish=()=>{const worn=slotOrder.map(slot=>outfit[slot]?.garment.name).filter((value,index,array)=>value&&array.indexOf(value)===index) as string[];const ending=worn.length>1?`${worn.slice(0,-1).join(', ')}과 ${worn.at(-1)}`:worn[0];const text=`${ending}으로 한복을 완성했어요!`;setMessage(text);setFinished(true);speakKorean(text,soundOn)};
  const reset=()=>{setOutfit({});setSelected(null);setPending(null);setFinished(false);setMessage('새 한복을 입혀 보세요.')};
  return <section className="hb-design" onPointerMove={move} onPointerUp={up} onPointerCancel={()=>setDrag(null)}><aside className="hb-closet"><h2>한복 옷장</h2><div className="hb-tabs">{categories.map(name=><button key={name} className={category===name?'active':''} onClick={()=>setCategory(name)}>{name}</button>)}</div><div className="hb-garments">{garments.filter(value=>value.name===category).map(garment=><button key={garment.id} className={pending?.id===garment.id?'selected':''} onPointerDown={event=>down(garment,event)}><img src={garment.img} alt=""/><b>{garment.variant}</b></button>)}</div></aside><section className="hb-stage-panel"><div className="hb-character-switch"><button className={kind===0?'active':''} onClick={()=>setKind(0)}>어린이 1</button><button className={kind===1?'active':''} onClick={()=>setKind(1)}>어린이 2</button></div><div ref={stage} className="hb-drop-stage" onClickCapture={()=>pending&&equip(pending)}><Character kind={kind} outfit={outfit} selected={selected} onSelect={selectLayer}/></div><p className="hb-message">{message}</p><div className="hb-stage-actions"><Button variant="outline" onClick={()=>selected&&setOutfit(value=>{const next={...value};delete next[selected];setSelected(null);return next})}>벗기기</Button><Button className="hb-finish" onClick={finish} disabled={!Object.keys(outfit).length}>완성하기</Button></div></section><aside className="hb-tools"><h2>색과 무늬</h2><p>{selected?outfit[selected]?.garment.name:'먼저 옷을 입혀요'}</p><div className="hb-colors">{colors.map(([name,color])=><button key={name} title={name} style={{background:color}} onClick={()=>change({color})}>{name}</button>)}</div><h3>무늬</h3><div className="hb-patterns">{patterns.map(pattern=><button key={pattern} className={selected&&outfit[selected]?.pattern===pattern?'active':''} onClick={()=>change({pattern})}>{pattern}</button>)}</div></aside>{drag&&<div className="hb-drag-ghost" style={{left:drag.x,top:drag.y}}><img src={drag.garment.img} alt=""/></div>}{finished&&<div className="hb-complete-overlay"><div><h2>한복 완성!</h2><Character kind={kind} outfit={outfit}/><p>{message}</p><nav><Button onClick={reset}>다른 한복 만들기</Button><Button variant="outline" onClick={()=>setFinished(false)}>다시 입히기</Button><Button variant="outline" onClick={onNames}>한복 이름 맞히기</Button><Button variant="outline" onClick={home}>처음으로</Button></nav></div></div>}</section>;
}

function ExploreNames({soundOn}:{soundOn:boolean}){const [girlSelected,setGirlSelected]=useState<Slot|null>(null);const [boySelected,setBoySelected]=useState<Slot|null>(null);const [coatSelected,setCoatSelected]=useState(false);const [showLabels,setShowLabels]=useState(false);const choose=(name:GarmentName,side:'girl'|'boy',slot:Slot)=>{side==='girl'?setGirlSelected(slot):setBoySelected(slot);setCoatSelected(false);speakKorean(messages[name],soundOn)};const labelFor=(outfit:Outfit)=>showLabels?Object.fromEntries(Object.entries(outfit).map(([slot,worn])=>[slot,worn!.garment.name])):{};return <section className="hb-name-explore"><div className="hb-name-instructions"><h3>알고 싶은 한복을 눌러보세요!</h3><Button variant="outline" onClick={()=>setShowLabels(value=>!value)}>{showLabels?'이름표 숨기기':'이름표 보기'}</Button></div><div className="hb-pair"><article><h3>치마 한복</h3><Character kind={0} outfit={girlOutfit} selected={girlSelected} labels={labelFor(girlOutfit)} onSelect={slot=>choose(girlOutfit[slot]!.garment.name,'girl',slot)} side="girl"/></article><article><h3>바지 한복</h3><Character kind={1} outfit={boyOutfit} selected={boySelected} labels={labelFor(boyOutfit)} onSelect={slot=>choose(boyOutfit[slot]!.garment.name,'boy',slot)} side="boy"/></article><button className={`hb-coat-card ${coatSelected?'selected':''}`} onClick={()=>{setCoatSelected(true);setGirlSelected(null);setBoySelected(null);speakKorean(messages.두루마기,soundOn)}}><img src={root+'durumagi-complete-v2.png'} alt="두루마기 전체" draggable={false}/><b>두루마기</b></button></div><div className="hb-big-name">{coatSelected?'두루마기':girlSelected?girlOutfit[girlSelected]?.garment.name:boySelected?boyOutfit[boySelected]?.garment.name:'옷을 눌러 보세요'}</div></section>}

function PictureCards({soundOn}:{soundOn:boolean}){
  const [order,setOrder]=useState(()=>[...names].sort(()=>Math.random()-.5));const [index,setIndex]=useState(0);const [choices,setChoices]=useState<GarmentName[]>([]);const [selected,setSelected]=useState<GarmentName|null>(null);const [answered,setAnswered]=useState(false);const [message,setMessage]=useState('그림과 알맞은 이름을 연결해요.');const [drag,setDrag]=useState<{name:GarmentName;x:number;y:number}|null>(null);const drop=useRef<HTMLButtonElement>(null);const timer=useRef<number|null>(null);const current=order[index];
  useEffect(()=>{setChoices([current,...names.filter(value=>value!==current).sort(()=>Math.random()-.5).slice(0,2)].sort(()=>Math.random()-.5));setSelected(null);setAnswered(false);setMessage('그림과 알맞은 이름을 연결해요.')},[current]);
  useEffect(()=>()=>{if(timer.current)window.clearTimeout(timer.current)},[]);
  const next=()=>{if(index===order.length-1){setOrder([...names].sort(()=>Math.random()-.5));setIndex(0)}else setIndex(value=>value+1)};
  const answer=(name:GarmentName)=>{if(answered)return;if(name===current){setAnswered(true);setMessage(`${messages[current]} 다음 그림으로 넘어가요!`);setSelected(null);playCorrectSound(soundOn);timer.current=window.setTimeout(next,900)}else{setSelected(null);setMessage(hints[current])}};
  const down=(name:GarmentName,event:React.PointerEvent)=>{event.currentTarget.setPointerCapture(event.pointerId);setSelected(name);setDrag({name,x:event.clientX,y:event.clientY-60});event.preventDefault();speakKorean(messages[name],soundOn)};
  const move=(event:React.PointerEvent)=>drag&&setDrag({...drag,x:event.clientX,y:event.clientY-60});
  const up=(event:React.PointerEvent)=>{if(!drag)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.hb-word-drop');const rect=drop.current?.getBoundingClientRect();if(target===drop.current||(rect&&event.clientX>=rect.left-18&&event.clientX<=rect.right+18&&event.clientY>=rect.top-18&&event.clientY<=rect.bottom+18))answer(drag.name);setDrag(null)};
  return <section className="hb-picture-cards" onPointerMove={move} onPointerUp={up} onPointerCancel={()=>setDrag(null)}><h3>그림 보고 단어카드 맞히기</h3><div className={`hb-one-garment hb-picture-${current}`}><img src={findGarment(current).img} alt={`${current} 그림`} draggable={false}/></div><button ref={drop} className={`hb-word-drop ${answered?'correct':''}`} onClick={()=>selected&&answer(selected)}>{answered?current:selected?'여기에 붙이기':'이름표를 붙여요'}</button><div className="hb-word-options">{choices.map(name=><button key={name} className={selected===name?'selected':''} onPointerDown={event=>down(name,event)} disabled={answered}>{name}</button>)}</div><p>{message}</p>{drag&&<div className="hb-word-ghost" style={{left:drag.x,top:drag.y}}>{drag.name}</div>}</section>
}

type LabelCard={id:string;name:GarmentName;side:'girl'|'boy';slot:Slot};
const labelCards:LabelCard[]=[{id:'girl-top',name:'저고리',side:'girl',slot:'top'},{id:'boy-top',name:'저고리',side:'boy',slot:'top'},{id:'girl-bottom',name:'치마',side:'girl',slot:'bottom'},{id:'boy-bottom',name:'바지',side:'boy',slot:'bottom'},{id:'girl-socks',name:'버선',side:'girl',slot:'socks'},{id:'boy-socks',name:'버선',side:'boy',slot:'socks'},{id:'girl-shoes',name:'꽃신',side:'girl',slot:'shoes'},{id:'boy-shoes',name:'꽃신',side:'boy',slot:'shoes'},{id:'girl-ornament',name:'노리개',side:'girl',slot:'ornament'}];
function LabelMatch({soundOn}:{soundOn:boolean}){const [cards,setCards]=useState(()=>[...labelCards].sort(()=>Math.random()-.5));const [selected,setSelected]=useState<LabelCard|null>(null);const [done,setDone]=useState<string[]>([]);const [message,setMessage]=useState('이름표를 누르고 알맞은 옷을 눌러요.');const [drag,setDrag]=useState<{card:LabelCard;x:number;y:number}|null>(null);const girl=useRef<HTMLDivElement>(null);const boy=useRef<HTMLDivElement>(null);const place=(side:'girl'|'boy',slot:Slot,card=selected)=>{if(!card)return;if(card.side===side&&card.slot===slot){if(!done.includes(card.id)){setDone(value=>[...value,card.id]);playCorrectSound(soundOn)}setMessage(`${card.name} 이름표를 붙였어요!`);setSelected(null)}else{setMessage(hints[card.name]);setSelected(null)}};const down=(card:LabelCard,event:React.PointerEvent)=>{event.currentTarget.setPointerCapture(event.pointerId);setSelected(card);setDrag({card,x:event.clientX,y:event.clientY-60});event.preventDefault();speakKorean(messages[card.name],soundOn)};const move=(event:React.PointerEvent)=>drag&&setDrag({...drag,x:event.clientX,y:event.clientY-60});const up=(event:React.PointerEvent)=>{if(!drag)return;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-hb-side][data-hb-slot]');if(target){place(target.dataset.hbSide as 'girl'|'boy',target.dataset.hbSlot as Slot,drag.card)}setDrag(null)};const reset=()=>{setCards([...labelCards].sort(()=>Math.random()-.5));setSelected(null);setDone([]);setMessage('이름표가 새롭게 섞였어요.')};const complete=done.length===labelCards.length;return <section className="hb-label-match" onPointerMove={move} onPointerUp={up} onPointerCancel={()=>setDrag(null)}><h3>남녀 한복 이름표 붙이기</h3><div className="hb-pair hb-label-pair"><article ref={girl}><h4>치마 한복</h4><Character kind={0} outfit={girlOutfit} onSelect={slot=>place('girl',slot)} labels={Object.fromEntries(labelCards.filter(card=>card.side==='girl'&&done.includes(card.id)).map(card=>[card.slot,card.name]))} side="girl"/></article><article ref={boy}><h4>바지 한복</h4><Character kind={1} outfit={boyOutfit} onSelect={slot=>place('boy',slot)} labels={Object.fromEntries(labelCards.filter(card=>card.side==='boy'&&done.includes(card.id)).map(card=>[card.slot,card.name]))} side="boy"/></article></div><div className="hb-label-cards">{cards.filter(card=>!done.includes(card.id)).map(card=><button key={card.id} className={selected?.id===card.id?'selected':''} onPointerDown={event=>down(card,event)}>{card.name}</button>)}</div><p>{message}</p>{complete&&<div className="hb-same-different"><h3>이름표를 모두 붙였어요!</h3><p>두 한복에는 모두 저고리가 있어요. 한쪽은 치마를, 다른 한쪽은 바지를 입었어요.</p><Button onClick={reset}>다시 하기</Button></div>}{drag&&<div className="hb-word-ghost" style={{left:drag.x,top:drag.y}}>{drag.card.name}</div>}</section>}

function NamesActivity({soundOn}:{soundOn:boolean}){const [nameMode,setNameMode]=useState<NameMode>('explore');return <section className="hb-names"><nav><button className={nameMode==='explore'?'active':''} onClick={()=>setNameMode('explore')}>1. 옷 눌러보기</button><button className={nameMode==='cards'?'active':''} onClick={()=>setNameMode('cards')}>2. 단어카드 맞히기</button><button className={nameMode==='labels'?'active':''} onClick={()=>setNameMode('labels')}>3. 이름표 붙이기</button></nav>{nameMode==='explore'&&<ExploreNames soundOn={soundOn}/>} {nameMode==='cards'&&<PictureCards soundOn={soundOn}/>} {nameMode==='labels'&&<LabelMatch soundOn={soundOn}/>}</section>}

export default function HanbokStudio({home,soundOn,toggleSound}:Props){const [mode,setMode]=useState<Mode>('start');const back=()=>{stopKoreanSpeech();setMode('start')};const title=mode==='design'?'한복 디자인하기':mode==='names'?'한복 이름 맞히기':'알록달록 한복 디자인실';return <main className="activity hb-app"><Header title={title} back={back} home={home} soundOn={soundOn} toggleSound={toggleSound}/>{mode==='start'&&<section className="hb-home"><div><span>한복을 입히고 이름도 배워요</span><h2>알록달록 한복 디자인실</h2><p>여러 가지 한복을 입혀 보고 한복의 이름도 알아보아요!</p></div><nav><button onClick={()=>setMode('design')}><img src={root+'jeogori-1.png'} alt=""/><b>한복 디자인하기</b><small>옷 조각을 직접 입혀요</small></button><button onClick={()=>setMode('names')}><img src={root+'norigae.png'} alt=""/><b>한복 이름 맞히기</b><small>그림과 7가지 이름을 연결해요</small></button></nav></section>}{mode==='design'&&<Design soundOn={soundOn} onNames={()=>setMode('names')} home={home}/>} {mode==='names'&&<NamesActivity soundOn={soundOn}/>}</main>}
