'use client';
import {useMemo,useRef,useState,type CSSProperties} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {FINISHED,WAITING,initialPieces,makeYutThrow,movePath,possibleRoutes,resolveMove,type Face,type Piece,type ResultName,type Route,type Team,type ThrowResult} from './yut-logic';
import {speakKorean} from './korean-speech';
import HomeIconButton from './home-icon-button';
import SoundIconButton from './sound-icon-button';
import './yut-game.css';

type Mode='start'|'practice'|'names'|'rules'|'game';
const asset='/yut-assets/';
const resultNames:ResultName[]=['도','개','걸','윷','모','백도'];
const icon:Record<ResultName,string>={도:'do_icon.png',개:'gae_icon.png',걸:'geol_icon.png',윷:'yut_icon.png',모:'mo_icon.png',백도:'backdo_icon.png'};
const countWords=['','하나','둘','셋','넷','다섯'];
const stickScatters=[
 [{x:27,y:33,r:-24},{x:44,y:67,r:12},{x:65,y:38,r:25},{x:76,y:69,r:-13}],
 [{x:23,y:64,r:20},{x:43,y:31,r:-15},{x:63,y:66,r:31},{x:79,y:39,r:-27}],
 [{x:28,y:29,r:-31},{x:38,y:70,r:16},{x:62,y:45,r:-6},{x:79,y:70,r:29}],
 [{x:22,y:42,r:9},{x:45,y:65,r:-29},{x:66,y:29,r:18},{x:79,y:59,r:-8}],
] as const;
const raw=[[1040,1040],[1040,868],[1040,696],[1040,524],[1040,352],[1040,180],[868,180],[696,180],[524,180],[352,180],[180,180],[180,352],[180,524],[180,696],[180,868],[180,1040],[352,1040],[524,1040],[696,1040],[868,1040],[352,352],[481,481],[739,481],[868,352],[610,610],[352,868],[481,739],[739,739],[868,868]];
const nodes=raw.map(([x,y],id)=>({id,x:x/1254*100,y:y/1254*100}));
const nodeMap=new Map(nodes.map(n=>[n.id,n]));

const speak=speakKorean;
function audioContext(){if(typeof window==='undefined')return null;const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;return new AudioContextClass()}
function playThrowSound(enabled:boolean){if(!enabled)return;const ctx=audioContext();if(!ctx)return;const start=ctx.currentTime;[0,.055,.125,.205,.285].forEach((delay,index)=>{const at=start+delay;const duration=.075+index*.008;const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const envelope=Math.pow(1-i/data.length,3.2);data[i]=(Math.random()*2-1)*envelope}const noise=ctx.createBufferSource();const filter=ctx.createBiquadFilter();const gain=ctx.createGain();noise.buffer=buffer;filter.type='bandpass';filter.frequency.setValueAtTime(720+index*85,at);filter.Q.setValueAtTime(2.4,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.32,at+.004);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);noise.connect(filter).connect(gain).connect(ctx.destination);noise.start(at);noise.stop(at+duration);const knock=ctx.createOscillator();const knockGain=ctx.createGain();knock.type='triangle';knock.frequency.setValueAtTime(155+index*13,at);knock.frequency.exponentialRampToValueAtTime(92,at+duration);knockGain.gain.setValueAtTime(.13,at);knockGain.gain.exponentialRampToValueAtTime(.0001,at+duration);knock.connect(knockGain).connect(ctx.destination);knock.start(at);knock.stop(at+duration)});window.setTimeout(()=>ctx.close(),900)}
function playArrivalSound(enabled:boolean){if(!enabled)return;const ctx=audioContext();if(!ctx)return;const start=ctx.currentTime;[523,659,784,1046].forEach((frequency,index)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();const at=start+index*.12;osc.type='sine';osc.frequency.setValueAtTime(frequency,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.17,at+.02);gain.gain.exponentialRampToValueAtTime(.0001,at+.22);osc.connect(gain).connect(ctx.destination);osc.start(at);osc.stop(at+.24)});window.setTimeout(()=>ctx.close(),1200)}
function pawnSrc(team:Team,count:number){return`${asset}${team}_${count>1?'mal_stack':'mal'}.png`}
function Pawn({team,count=1,selectable=false,onClick,onPointerDown}:{team:Team;count?:number;selectable?:boolean;onClick?:()=>void;onPointerDown?:(event:React.PointerEvent<HTMLButtonElement>)=>void}){return <button type="button" className={`png-pawn ${team} ${selectable?'selectable':''}`} onClick={event=>{if(!onPointerDown||event.detail===0)onClick?.()}} onPointerDown={onPointerDown} disabled={!selectable} aria-label={`${team==='red'?'빨강':'파랑'}팀 말 ${count}개`}><img src={pawnSrc(team,count)} alt=""/>{count>1&&<b>2</b>}</button>}
function ResultIcon({name}:{name:ResultName}){return <img className="result-png" src={`${asset}icons/${icon[name]}`} alt=""/>}

function YutSticks({faces,rolling,onThrow,disabled}:{faces:Face[];rolling:boolean;onThrow:()=>void;disabled:boolean}){
 const start=useRef<number|null>(null);
 const[scatter,setScatter]=useState(0);
 const throwNow=()=>{if(disabled)return;setScatter(v=>(v+1)%stickScatters.length);onThrow()};
 const layout=stickScatters[scatter];
 return <section className="png-throw-zone"><div className="throw-mat"><img className="mat-png" src={`${asset}yut_throw_mat.png`} alt="전통 윷 던지기 놀이판"/><div className={`png-sticks ${rolling?'rolling':''}`} onPointerDown={e=>{start.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(start.current!==null&&start.current-e.clientY>35)throwNow();start.current=null}}>{faces.map((face,i)=>{const spot=layout[i];const style={'--stick-x':`${spot.x}%`,'--stick-y':`${spot.y}%`,'--stick-r':`${spot.r}deg`,'--stick-delay':`${i*.05}s`} as CSSProperties;return <span key={i} style={style}><img src={`${asset}yut_${face}.png`} alt={face==='round'?'둥근 면':face==='backdo'?'백도 표시 면':'평평한 면'}/></span>})}</div></div><Button className="png-throw-button" onClick={throwNow} disabled={disabled}>{rolling?'윷이 날아가요':'윷 던지기'}</Button><small>버튼을 누르거나 윷가락을 위로 밀어요</small></section>
}

type Target={display:number;actual:number;route:Route;label?:string};
function Board({pieces,selectable=[],targets=[],onPiece,onTarget}:{pieces:Piece[];selectable:string[];targets:Target[];onPiece:(id:string)=>void;onTarget:(t:Target)=>void}){const grouped=useMemo(()=>{const m=new Map<string,Piece[]>();pieces.filter(p=>p.position>=0).forEach(p=>{const k=`${p.team}-${p.position}`;m.set(k,[...(m.get(k)||[]),p])});return[...m.values()]},[pieces]);const[drag,setDrag]=useState<{id:string;team:Team;count:number;x:number;y:number}|null>(null);const startDrag=(id:string,team:Team,count:number,event:React.PointerEvent<HTMLButtonElement>)=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);setDrag({id,team,count,x:event.clientX,y:event.clientY-58});onPiece(id)};const moveDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(drag)setDrag({...drag,x:event.clientX,y:event.clientY-58})};const dropDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(!drag)return;const hit=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-yut-target]');const display=hit?Number(hit.dataset.yutTarget):NaN;const option=targets.find(target=>target.display===display);if(option)onTarget(option);setDrag(null)};return <div className="traditional-board" aria-label="정사각형 29밭 전통 윷판" onPointerMove={moveDrag} onPointerUp={dropDrag} onPointerCancel={()=>setDrag(null)}><img className="board-png" src={`${asset}traditional_yut_board.png`} alt="외곽 20밭과 X자 지름길이 있는 전통 윷판"/>{nodes.map(n=>{const options=targets.filter(t=>t.display===n.id);const option=options[0];return <button key={n.id} data-yut-target={n.id} className={`board-touch ${options.length?'target':''} ${n.id===0?'home':''}`} style={{left:`${n.x}%`,top:`${n.y}%`}} disabled={!options.length} onPointerUp={event=>{event.stopPropagation();if(option)onTarget(option)}} onKeyDown={event=>{if(option&&(event.key==='Enter'||event.key===' ')){event.preventDefault();onTarget(option)}}} aria-label={option?.label||(n.id===0?'출발과 도착':`${n.id}번 밭`)}>{n.id===0&&<span>출발·도착</span>}{option?.label&&<b className="route-choice-label">{option.label}</b>}</button>})}{grouped.map(group=>{const p=group[0],n=nodeMap.get(p.position)!;const active=group.find(x=>selectable.includes(x.id));const can=!!active;return <div key={`${p.team}-${p.position}`} className={`pawn-anchor ${p.team}`} style={{left:`${n.x}%`,top:`${n.y}%`}}><Pawn team={p.team} count={group.length} selectable={can} onClick={()=>onPiece(active?.id||p.id)} onPointerDown={event=>active&&startDrag(active.id,p.team,group.length,event)}/></div>})}{drag&&<div className="yut-drag-ghost" style={{left:drag.x,top:drag.y}}><img src={pawnSrc(drag.team,drag.count)} alt=""/></div>}</div>}

function Rules({close,start}:{close?:()=>void;start?:()=>void}){const steps=[['do_icon.png','1. 각 팀이 말을 출발점에 놓아요.'],['do_icon.png','2. 윷을 던져요.'],['gae_icon.png','3. 나온 수만큼 가요.'],['yut_icon.png','4. 같은 팀 말을 만나면 함께 가요.'],['geol_icon.png','5. 다른 팀 말을 만나면 잡아요.'],['mo_icon.png','6. 윷과 모는 한 번 더 던져요.'],['backdo_icon.png','7. 백도는 한 칸 뒤로 가요.'],['do_icon.png','8. 말 두 개가 먼저 도착하면 이겨요.']];return <dialog open className="png-yut-modal"><div className="png-rules"><h2>쉬운 윷놀이 규칙</h2><div>{steps.map(([src,text])=><article key={text}><img src={`${asset}icons/${src}`} alt=""/><b>{text}</b></article>)}</div><p>같이 놀며 천천히 익혀요!</p>{start?<Button onClick={start}>알았어요, 시작!</Button>:<Button onClick={close}>규칙 닫기</Button>}</div></dialog>}
function TeamPanel({team,name,pieces,active}:{team:Team;name:string;pieces:Piece[];active:boolean}){const mine=pieces.filter(p=>p.team===team);return <article className={`png-team ${team} ${active?'active':''}`}><div><img src={pawnSrc(team,1)} alt=""/><h3>{name}</h3></div><p><span>출발 전 <b>{mine.filter(p=>p.position===WAITING).length}</b></span><span>윷판 위 <b>{mine.filter(p=>p.position>=0).length}</b></span><span>도착 <b>{mine.filter(p=>p.position===FINISHED).length}</b></span></p></article>}

function Practice({soundOn,onBack}:{soundOn:boolean;onBack:()=>void}){const[faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[seen,setSeen]=useState<ResultName[]>([]);const[piece,setPiece]=useState<Piece>({id:'practice',team:'red',position:WAITING,route:'outer',history:[]});const[message,setMessage]=useState('도·개·걸·윷·모·백도를 만나 보세요!');const throwYut=()=>{if(rolling||result)return;const r=makeYutThrow();playThrowSound(soundOn);setRolling(true);setMessage('윷을 던지고 있어요!');window.setTimeout(()=>{setFaces(r.faces);setResult(r);setSeen(v=>v.includes(r.name)?v:[...v,r.name]);setMessage(r.sentence);setRolling(false);speak(r.sentence,soundOn);if(r.name==='백도'&&piece.position===WAITING){window.setTimeout(()=>{setResult(null);setMessage('윷판 위에 말이 없어서 다음 윷을 던져요.')},900)}},480)};const move=()=>{if(!result)return;const route=possibleRoutes(piece,result)[0];const solved=resolveMove([piece],'red','practice',result,route);const reached=solved.finalPieces[0].position===FINISHED;if(reached)playArrivalSound(soundOn);setPiece(reached?{...solved.finalPieces[0],position:WAITING}:solved.finalPieces[0]);setResult(null);setMessage(reached?'도착했어요! 다시 출발해요.':seen.length===6?'윷놀이 준비 완료!':'다시 윷을 던져 보세요!')};return <section className="practice-screen"><div className="practice-top"><Button variant="outline" onClick={onBack}>이전</Button><h2>윷놀이 연습</h2><div>{resultNames.map(n=><span className={seen.includes(n)?'seen':''} key={n}><ResultIcon name={n}/><b>{n}</b></span>)}</div></div><div className="practice-layout"><div className="practice-board"><Board pieces={piece.position>=0?[piece]:[]} selectable={result&&piece.position>=0?['practice']:[]} targets={[]} onPiece={move} onTarget={()=>{}}/>{piece.position===WAITING&&<div className="practice-wait"><Pawn team="red" selectable={!!result&&result.name!=='백도'} onClick={move}/><b>연습 말</b></div>}</div><aside><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={rolling||!!result}/><div className="png-result"><strong>{result?.name||'준비'}</strong><p>{message}</p></div>{seen.length===6&&<div className="ready-badge">윷놀이 준비 완료!</div>}</aside></div></section>}

type MovePlan={pieceId:string;route:Route;path:number[];index:number;movingIds:string[];basePieces:Piece[];throwResult:ThrowResult};
function Game({soundOn,names,onBack,onHome}:{soundOn:boolean;names:Record<Team,string>;onBack:()=>void;onHome:()=>void}){
 const[pieces,setPieces]=useState(initialPieces);const piecesRef=useRef(pieces);const moveLock=useRef(false);const[turn,setTurn]=useState<Team>('red');const[setupTeam,setSetupTeam]=useState<Team|null>('red');const[faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[moving,setMoving]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[last,setLast]=useState<ResultName|null>(null);const[selected,setSelected]=useState<string|null>(null);const[targets,setTargets]=useState<Target[]>([]);const[plan,setPlan]=useState<MovePlan|null>(null);const[message,setMessage]=useState(`${names.red} 말을 골라 출발점에 놓아요.`);const[bonus,setBonus]=useState(false);const[winner,setWinner]=useState<Team|null>(null);const[showRules,setShowRules]=useState(false);const[confirm,setConfirm]=useState<'home'|'restart'|null>(null);
 const selectable=useMemo(()=>setupTeam&&!moving?pieces.filter(p=>p.team===setupTeam&&p.position===WAITING).map(p=>p.id):result&&!moving&&!plan?pieces.filter(p=>p.team===turn&&p.position!==FINISHED&&(result.name!=='백도'||p.position>=0)).map(p=>p.id):[],[pieces,result,moving,plan,turn,setupTeam]);
 const nextTurn=()=>{const n=turn==='red'?'blue':'red';setTurn(n);setMessage(`${names[n]} 차례예요. 윷을 던져요!`);setBonus(false)};
 const throwYut=()=>{if(setupTeam||rolling||moving||result||winner)return;const r=makeYutThrow();playThrowSound(soundOn);setSelected(null);setTargets([]);setBonus(false);setRolling(true);setMessage('윷을 던지고 있어요!');window.setTimeout(()=>{setFaces(r.faces);setLast(r.name);setResult(r);setRolling(false);setMessage(`${r.sentence} 움직일 말을 골라요.`);speak(r.sentence,soundOn);if(r.name==='백도'&&!piecesRef.current.some(p=>p.team===turn&&p.position>=0)){setMessage('백도! 윷판 위에 말이 없어 다음 팀 차례예요.');window.setTimeout(()=>{setResult(null);nextTurn()},900)}},480)};
 const finishMove=(active:MovePlan)=>{const solved=resolveMove(active.basePieces,turn,active.pieceId,active.throwResult,active.route);piecesRef.current=solved.finalPieces;setPieces(solved.finalPieces);setMoving(false);setPlan(null);moveLock.current=false;setResult(null);setSelected(null);const arrived=solved.movingIds.some(id=>active.basePieces.find(piece=>piece.id===id)?.position!==FINISHED&&solved.finalPieces.find(piece=>piece.id===id)?.position===FINISHED);if(arrived){playArrivalSound(soundOn);setMessage('도착했어요!');speak('도착했어요!',soundOn)}if(solved.won){setWinner(turn);setMessage('축하해요! 두 개의 말이 모두 도착했어요!');speak(`${names[turn]} 승리! 두 개의 말이 모두 도착했어요!`,soundOn);return}if(solved.caughtIds.length){setMessage('상대 말을 잡았어요! 한 번 더 던져요.');speak('상대 말을 잡았어요! 한 번 더 던져요.',soundOn);setBonus(true)}else if(solved.extra){setMessage('한 번 더! 다시 윷을 던져요.');setBonus(true)}else window.setTimeout(nextTurn,arrived?650:0)};
 const beginMove=(route:Route,pieceId:string)=>{if(!result||moveLock.current)return;const basePieces=piecesRef.current;const chosen=basePieces.find(piece=>piece.id===pieceId);if(!chosen)return;const path=movePath(chosen,result,route);const stacked=basePieces.filter(piece=>piece.team===turn&&piece.position===chosen.position&&piece.position>=0).map(piece=>piece.id);const movingIds=stacked.length?stacked:[pieceId];const active:MovePlan={pieceId,route,path,index:0,movingIds,basePieces,throwResult:result};moveLock.current=true;setMoving(true);setPlan(active);const first=path[0];setTargets([{route,actual:first,display:first===FINISHED||first===WAITING?0:first,label:'1칸'}]);setMessage(`반짝이는 다음 칸을 눌러 ${result.steps<0?'뒤로 한 칸':'한 칸씩'} 움직여요.`)};
 const advance=(target:Target)=>{if(setupTeam&&selected&&target.actual===0){const placed=piecesRef.current.map(piece=>piece.id===selected?{...piece,position:0,route:'outer' as Route,history:[0]}:piece);piecesRef.current=placed;setPieces(placed);setSelected(null);setTargets([]);if(setupTeam==='red'){setTurn('blue');setSetupTeam('blue');setMessage(`${names.blue} 말을 골라 출발점에 놓아요.`)}else{setTurn('red');setSetupTeam(null);setMessage(`${names.red} 차례예요. 윷을 던져요!`)}return}if(!plan){if(selected)beginMove(target.route,selected);return}const node=plan.path[plan.index];if(target.actual!==node)return;const interim=piecesRef.current.map(piece=>plan.movingIds.includes(piece.id)?{...piece,position:node,route:plan.route}:piece);piecesRef.current=interim;setPieces(interim);speak(plan.throwResult.name==='백도'?'뒤로 한 칸':countWords[plan.index+1]||'도착',soundOn);const nextIndex=plan.index+1;if(nextIndex<plan.path.length){const nextNode=plan.path[nextIndex];setPlan({...plan,index:nextIndex});setTargets([{route:plan.route,actual:nextNode,display:nextNode===FINISHED||nextNode===WAITING?0:nextNode,label:`${nextIndex+1}칸`}]);setMessage(`${nextIndex+1}번째 반짝이는 칸을 눌러요.`)}else{setTargets([]);finishMove(plan)}};
 const choose=(id:string)=>{const piece=pieces.find(value=>value.id===id);if(!piece||!selectable.includes(id)||moving||plan)return;if(setupTeam){setSelected(id);setTargets([{route:'outer',actual:0,display:0,label:'출발점'}]);setMessage(`${names[setupTeam]} 말을 골랐어요. 반짝이는 출발점을 눌러요.`);return}if(!result)return;const routes=possibleRoutes(piece,result);setSelected(id);if(routes.length===1){beginMove(routes[0],id);return}const routeTargets=routes.map(route=>{const first=movePath(piece,result,route)[0];const label=route==='outer'?'바깥길':route==='center_to_bl'?'왼쪽 길':route==='center_to_home'?'오른쪽 길':'지름길';return{route,actual:first,display:first===FINISHED||first===WAITING?0:first,label}});setTargets(routeTargets);setMessage('반짝이는 바깥길과 지름길 중 가고 싶은 길을 눌러요.')};
 const reset=()=>{const fresh=initialPieces();piecesRef.current=fresh;moveLock.current=false;setPieces(fresh);setTurn('red');setSetupTeam('red');setFaces(['round','flat','round','flat']);setRolling(false);setMoving(false);setPlan(null);setResult(null);setLast(null);setSelected(null);setTargets([]);setWinner(null);setBonus(false);setMessage(`${names.red} 말을 골라 출발점에 놓아요.`);setConfirm(null)};
 return <section className="png-game"><div className="game-board-column"><div className="board-heading"><h2>전통 윷판</h2><span>출발·도착은 오른쪽 아래예요</span></div><Board pieces={pieces} selectable={plan?plan.movingIds:selectable} targets={targets} onPiece={choose} onTarget={advance}/></div><aside className="game-side"><div className="side-actions"><Button variant="outline" onClick={()=>setShowRules(true)}>규칙 다시 보기</Button><Button variant="outline" disabled={!result&&!setupTeam} onClick={()=>{if(setupTeam)setMessage('대기 말을 골라 출발점을 눌러요.');else if(targets.length)setMessage('반짝이는 칸을 한 칸씩 눌러요.');else if(selected)choose(selected);else setMessage('반짝이는 말을 골라요.')}}>힌트</Button><Button variant="outline" onClick={()=>setConfirm('restart')}>처음부터</Button></div><div className="turn-box"><span>{setupTeam?'출발 준비':'현재 차례'}</span><strong className={turn}>{names[turn]}</strong><small>직전 결과: {last||'없음'}</small>{bonus&&<b>한 번 더!</b>}</div><div className="team-row"><TeamPanel team="red" name={names.red} pieces={pieces} active={turn==='red'}/><TeamPanel team="blue" name={names.blue} pieces={pieces} active={turn==='blue'}/></div><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={!!setupTeam||rolling||moving||!!result||!!winner}/><div className="result-guide"><div className="result-strip">{resultNames.map(name=><span className={last===name?'active':''} key={name}><ResultIcon name={name}/><b>{name}</b></span>)}</div><div className="png-result"><strong>{setupTeam?'말 놓기':result?.name||last||'준비'}</strong><p>{message}</p></div></div><div className="waiting-area"><div><b>빨강팀 대기</b>{pieces.filter(piece=>piece.team==='red'&&piece.position===WAITING).map(piece=><Pawn key={piece.id} team="red" selectable={selectable.includes(piece.id)} onClick={()=>choose(piece.id)}/>)}</div><div><b>파랑팀 대기</b>{pieces.filter(piece=>piece.team==='blue'&&piece.position===WAITING).map(piece=><Pawn key={piece.id} team="blue" selectable={selectable.includes(piece.id)} onClick={()=>choose(piece.id)}/>)}</div></div></aside>{showRules&&<Rules close={()=>setShowRules(false)}/>} {confirm&&<dialog open className="png-yut-modal"><div className="confirm-card"><h2>{confirm==='home'?'처음 화면으로 갈까요?':'새로 시작할까요?'}</h2><p>지금까지의 놀이는 사라져요.</p><div><Button variant="outline" onClick={()=>setConfirm(null)}>계속 놀기</Button><Button onClick={()=>confirm==='home'?onHome():reset()}>네, 시작해요</Button></div></div></dialog>}{winner&&<dialog open className="png-yut-modal"><div className="victory-card"><img src={pawnSrc(winner,2)} alt="업힌 윷말"/><h2>{names[winner]} 승리!</h2><p>축하해요! 두 개의 말이 모두 도착했어요!</p><div><Button onClick={reset}>같은 팀으로 다시 하기</Button><Button variant="outline" onClick={onBack}>팀 바꾸기</Button><HomeIconButton onClick={onHome}/></div></div></dialog>}<button className="game-home-guard" onClick={()=>setConfirm('home')} aria-label="게임을 끝내고 홈으로"/></section>}

export default function YutGame({home,soundOn,toggleSound}:{home:()=>void;soundOn:boolean;toggleSound:()=>void}){const[mode,setMode]=useState<Mode>('start');const[names,setNames]=useState<Record<Team,string>>({red:'빨강팀',blue:'파랑팀'});const guardedHome=()=>mode==='game'?document.querySelector<HTMLButtonElement>('.game-home-guard')?.click():home();return <main className="activity png-yut-app"><header className="topbar"><HomeIconButton onClick={guardedHome}/><div className="activity-title"><h1>함께하는 윷놀이</h1></div><SoundIconButton soundOn={soundOn} onClick={toggleSound} className="round-action sound-only"/></header>{mode==='start'&&<section className="png-yut-start"><h2>윷을 던지고 나온 수만큼 말을 움직여요!</h2><div><button onClick={()=>setMode('practice')}><img src={`${asset}yut_flat.png`} alt="윷가락"/><b>윷놀이 연습</b><small>도·개·걸·윷·모·백도를 익혀요</small></button><button onClick={()=>setMode('names')}><img src={`${asset}traditional_yut_board.png`} alt="전통 정사각형 윷판"/><b>함께 윷놀이</b><small>빨강팀과 파랑팀이 함께 놀아요</small></button></div></section>}{mode==='practice'&&<Practice soundOn={soundOn} onBack={()=>setMode('start')}/>} {mode==='names'&&<section className="png-team-names"><Button variant="outline" onClick={()=>setMode('start')}>이전</Button><div><img src={`${asset}red_mal.png`} alt="빨강팀 말"/><img src={`${asset}blue_mal.png`} alt="파랑팀 말"/><h2>팀 이름을 정해요</h2><label>빨강 줄무늬 팀<Input value={names.red} maxLength={8} onChange={e=>setNames({...names,red:e.target.value||'빨강팀'})}/></label><label>파랑 꽃무늬 팀<Input value={names.blue} maxLength={8} onChange={e=>setNames({...names,blue:e.target.value||'파랑팀'})}/></label><Button onClick={()=>setMode('rules')}>게임 시작</Button></div></section>}{mode==='rules'&&<Rules start={()=>setMode('game')}/>} {mode==='game'&&<Game key={`${names.red}-${names.blue}`} soundOn={soundOn} names={names} onBack={()=>setMode('names')} onHome={home}/>}</main>}
