'use client';
import {useMemo,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {FINISHED,WAITING,initialPieces,makeYutThrow,moveTarget,possibleRoutes,resolveMove,type Face,type Piece,type ResultName,type Route,type Team,type ThrowResult} from './yut-logic';
import {speakKorean} from './korean-speech';
import './yut-game.css';

type Mode='start'|'practice'|'names'|'rules'|'game';
const asset='/yut-assets/';
const resultNames:ResultName[]=['도','개','걸','윷','모','백도'];
const icon:Record<ResultName,string>={도:'do_icon.png',개:'gae_icon.png',걸:'geol_icon.png',윷:'yut_icon.png',모:'mo_icon.png',백도:'backdo_icon.png'};
const countWords=['','하나','둘','셋','넷','다섯'];
const raw=[[1040,1040],[1040,868],[1040,696],[1040,524],[1040,352],[1040,180],[868,180],[696,180],[524,180],[352,180],[180,180],[180,352],[180,524],[180,696],[180,868],[180,1040],[352,1040],[524,1040],[696,1040],[868,1040],[352,352],[481,481],[739,481],[868,352],[610,610],[352,868],[481,739],[739,739],[868,868]];
const nodes=raw.map(([x,y],id)=>({id,x:x/1254*100,y:y/1254*100}));
const nodeMap=new Map(nodes.map(n=>[n.id,n]));

const speak=speakKorean;
function pawnSrc(team:Team,count:number){return`${asset}${team}_${count>1?'mal_stack':'mal'}.png`}
function Pawn({team,count=1,selectable=false,onClick}:{team:Team;count?:number;selectable?:boolean;onClick?:()=>void}){return <button type="button" className={`png-pawn ${team} ${selectable?'selectable':''}`} onClick={onClick} disabled={!selectable} aria-label={`${team==='red'?'빨강':'파랑'}팀 말 ${count}개`}><img src={pawnSrc(team,count)} alt=""/>{count>1&&<b>2</b>}</button>}
function ResultIcon({name}:{name:ResultName}){return <img className="result-png" src={`${asset}icons/${icon[name]}`} alt=""/>}

function YutSticks({faces,rolling,onThrow,disabled}:{faces:Face[];rolling:boolean;onThrow:()=>void;disabled:boolean}){const start=useRef<number|null>(null);return <section className="png-throw-zone"><div className="throw-mat"><img className="mat-png" src={`${asset}yut_throw_mat.png`} alt="전통 윷 던지기 놀이판"/><div className={`png-sticks ${rolling?'rolling':''}`} onPointerDown={e=>{start.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{if(start.current!==null&&start.current-e.clientY>35&&!disabled)onThrow();start.current=null}}>{faces.map((face,i)=><img key={i} src={`${asset}yut_${face}.png`} alt={face==='round'?'둥근 면':face==='backdo'?'백도 표시 면':'평평한 면'}/>)}</div></div><Button className="png-throw-button" onClick={onThrow} disabled={disabled}>{rolling?'윷이 날아가요':'윷 던지기'}</Button><small>버튼을 누르거나 윷가락을 위로 밀어요</small></section>}

type Target={display:number;actual:number;route:Route};
function Board({pieces,selectable=[],targets=[],onPiece,onTarget}:{pieces:Piece[];selectable:string[];targets:Target[];onPiece:(id:string)=>void;onTarget:(t:Target)=>void}){const grouped=useMemo(()=>{const m=new Map<string,Piece[]>();pieces.filter(p=>p.position>=0).forEach(p=>{const k=`${p.team}-${p.position}`;m.set(k,[...(m.get(k)||[]),p])});return[...m.values()]},[pieces]);return <div className="traditional-board" aria-label="정사각형 29밭 전통 윷판"><img className="board-png" src={`${asset}traditional_yut_board.png`} alt="외곽 20밭과 X자 지름길이 있는 전통 윷판"/>{nodes.map(n=>{const options=targets.filter(t=>t.display===n.id);return <button key={n.id} className={`board-touch ${options.length?'target':''} ${n.id===0?'home':''}`} style={{left:`${n.x}%`,top:`${n.y}%`}} disabled={!options.length} onClick={()=>options[0]&&onTarget(options[0])} aria-label={n.id===0?'출발과 도착':`${n.id}번 밭`}>{n.id===0&&<span>출발·도착</span>}</button>})}{grouped.map(group=>{const p=group[0],n=nodeMap.get(p.position)!;const can=group.some(x=>selectable.includes(x.id));return <div key={`${p.team}-${p.position}`} className="pawn-anchor" style={{left:`${n.x}%`,top:`${n.y}%`}}><Pawn team={p.team} count={group.length} selectable={can} onClick={()=>onPiece(group.find(x=>selectable.includes(x.id))?.id||p.id)}/></div>})}</div>}

function Rules({close,start}:{close?:()=>void;start?:()=>void}){const steps=[['do_icon.png','1. 윷을 던져요.'],['gae_icon.png','2. 나온 수만큼 가요.'],['yut_icon.png','3. 같은 팀 말을 만나면 함께 가요.'],['geol_icon.png','4. 다른 팀 말을 만나면 잡아요.'],['mo_icon.png','5. 윷과 모는 한 번 더 던져요.'],['backdo_icon.png','6. 백도는 한 칸 뒤로 가요.'],['do_icon.png','7. 말 두 개가 먼저 도착하면 이겨요.']];return <dialog open className="png-yut-modal"><div className="png-rules"><h2>쉬운 윷놀이 규칙</h2><div>{steps.map(([src,text])=><article key={text}><img src={`${asset}icons/${src}`} alt=""/><b>{text}</b></article>)}</div><p>같이 놀며 천천히 익혀요!</p>{start?<Button onClick={start}>알았어요, 시작!</Button>:<Button onClick={close}>규칙 닫기</Button>}</div></dialog>}
function TeamPanel({team,name,pieces,active}:{team:Team;name:string;pieces:Piece[];active:boolean}){const mine=pieces.filter(p=>p.team===team);return <article className={`png-team ${team} ${active?'active':''}`}><div><img src={pawnSrc(team,1)} alt=""/><h3>{name}</h3></div><p><span>출발 전 <b>{mine.filter(p=>p.position===WAITING).length}</b></span><span>윷판 위 <b>{mine.filter(p=>p.position>=0).length}</b></span><span>도착 <b>{mine.filter(p=>p.position===FINISHED).length}</b></span></p></article>}

function Practice({soundOn,onBack}:{soundOn:boolean;onBack:()=>void}){const[faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[seen,setSeen]=useState<ResultName[]>([]);const[piece,setPiece]=useState<Piece>({id:'practice',team:'red',position:WAITING,route:'outer',history:[]});const[message,setMessage]=useState('도·개·걸·윷·모·백도를 만나 보세요!');const throwYut=()=>{if(rolling||result)return;setRolling(true);setTimeout(()=>{const r=makeYutThrow();setFaces(r.faces);setResult(r);setSeen(v=>v.includes(r.name)?v:[...v,r.name]);setMessage(r.sentence);speak(r.sentence,soundOn);setRolling(false);if(r.name==='백도'&&piece.position===WAITING){setTimeout(()=>{setResult(null);setMessage('윷판 위에 말이 없어서 다음 윷을 던져요.')},700)}},800)};const move=()=>{if(!result)return;const route=possibleRoutes(piece,result)[0];const solved=resolveMove([piece],'red','practice',result,route);setPiece(solved.finalPieces[0].position===FINISHED?{...solved.finalPieces[0],position:WAITING}:solved.finalPieces[0]);setResult(null);setMessage(seen.length===6?'윷놀이 준비 완료!':'다시 윷을 던져 보세요!')};return <section className="practice-screen"><div className="practice-top"><Button variant="outline" onClick={onBack}>이전</Button><h2>윷놀이 연습</h2><div>{resultNames.map(n=><span className={seen.includes(n)?'seen':''} key={n}><ResultIcon name={n}/><b>{n}</b></span>)}</div></div><div className="practice-layout"><div className="practice-board"><Board pieces={piece.position>=0?[piece]:[]} selectable={result&&piece.position>=0?['practice']:[]} targets={[]} onPiece={move} onTarget={()=>{}}/>{piece.position===WAITING&&<div className="practice-wait"><Pawn team="red" selectable={!!result&&result.name!=='백도'} onClick={move}/><b>연습 말</b></div>}</div><aside><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={rolling||!!result}/><div className="png-result"><strong>{result?.name||'준비'}</strong><p>{message}</p></div>{seen.length===6&&<div className="ready-badge">윷놀이 준비 완료!</div>}</aside></div></section>}

function Game({soundOn,names,onBack,onHome}:{soundOn:boolean;names:Record<Team,string>;onBack:()=>void;onHome:()=>void}){const[pieces,setPieces]=useState(initialPieces);const piecesRef=useRef(pieces);const[turn,setTurn]=useState<Team>('red');const[faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[moving,setMoving]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[last,setLast]=useState<ResultName|null>(null);const[selected,setSelected]=useState<string|null>(null);const[targets,setTargets]=useState<Target[]>([]);const[message,setMessage]=useState(`${names.red} 차례예요. 윷을 던져요!`);const[bonus,setBonus]=useState(false);const[winner,setWinner]=useState<Team|null>(null);const[showRules,setShowRules]=useState(false);const[confirm,setConfirm]=useState<'home'|'restart'|null>(null);const selectable=useMemo(()=>result&&!moving?pieces.filter(p=>p.team===turn&&p.position!==FINISHED&&(result.name!=='백도'||p.position>=0)).map(p=>p.id):[],[pieces,result,moving,turn]);
 const nextTurn=()=>{const n=turn==='red'?'blue':'red';setTurn(n);setMessage(`${names[n]} 차례예요. 윷을 던져요!`);setBonus(false)};
 const throwYut=()=>{if(rolling||moving||result||winner)return;setRolling(true);setSelected(null);setTargets([]);setTimeout(()=>{const r=makeYutThrow();setFaces(r.faces);setLast(r.name);setRolling(false);speak(r.sentence,soundOn);if(r.name==='백도'&&!piecesRef.current.some(p=>p.team===turn&&p.position>=0)){setMessage('백도! 윷판 위에 말이 없어 다음 팀 차례예요.');setTimeout(nextTurn,800);return}setResult(r);setMessage(`${r.sentence} 움직일 말을 골라요.`)},800)};
 const choose=(id:string)=>{if(!result||moving)return;const p=pieces.find(x=>x.id===id);if(!p||!selectable.includes(id))return;const t=possibleRoutes(p,result).map(route=>{const actual=moveTarget(p,result,route);return{route,actual,display:actual===FINISHED||actual===WAITING?0:actual}});setSelected(id);setTargets(t);setMessage(t.length>1?'바깥길과 지름길 중 가고 싶은 길을 골라요.':'반짝이는 도착 밭을 눌러요.')};
 const move=async(t:Target)=>{if(!result||!selected||moving)return;const solved=resolveMove(piecesRef.current,turn,selected,result,t.route);setMoving(true);setTargets([]);for(let i=0;i<solved.path.length;i++){await new Promise(r=>setTimeout(r,300));const node=solved.path[i];if(node>=0){const next=piecesRef.current.map(p=>solved.movingIds.includes(p.id)?{...p,position:node,route:t.route}:p);piecesRef.current=next;setPieces(next);speak(countWords[i+1]||'도착',soundOn)}}piecesRef.current=solved.finalPieces;setPieces(solved.finalPieces);setMoving(false);setResult(null);setSelected(null);if(solved.won){setWinner(turn);setMessage('축하해요! 두 개의 말이 모두 도착했어요!');speak(`${names[turn]} 승리! 두 개의 말이 모두 도착했어요!`,soundOn);return}if(solved.caughtIds.length){setMessage('상대 말을 잡았어요! 한 번 더 던져요.');speak('상대 말을 잡았어요! 한 번 더 던져요.',soundOn);setBonus(true)}else if(solved.extra){setMessage('한 번 더! 다시 윷을 던져요.');setBonus(true)}else nextTurn()};
 const reset=()=>{const fresh=initialPieces();piecesRef.current=fresh;setPieces(fresh);setTurn('red');setFaces(['round','flat','round','flat']);setRolling(false);setMoving(false);setResult(null);setLast(null);setSelected(null);setTargets([]);setWinner(null);setBonus(false);setMessage(`${names.red} 차례예요. 윷을 던져요!`);setConfirm(null)};
 return <section className="png-game"><div className="game-board-column"><div className="board-heading"><h2>전통 윷판</h2><span>출발·도착은 오른쪽 아래예요</span></div><Board pieces={pieces} selectable={selectable} targets={targets} onPiece={choose} onTarget={move}/></div><aside className="game-side"><div className="side-actions"><Button variant="outline" onClick={()=>setShowRules(true)}>규칙 다시 보기</Button><Button variant="outline" disabled={!result} onClick={()=>selected?choose(selected):setMessage('반짝이는 말을 골라요.')}>힌트</Button><Button variant="outline" onClick={()=>setConfirm('restart')}>처음부터</Button></div><div className="turn-box"><span>현재 차례</span><strong className={turn}>{names[turn]}</strong><small>직전 결과: {last||'없음'}</small>{bonus&&<b>한 번 더!</b>}</div><div className="team-row"><TeamPanel team="red" name={names.red} pieces={pieces} active={turn==='red'}/><TeamPanel team="blue" name={names.blue} pieces={pieces} active={turn==='blue'}/></div><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={rolling||moving||!!result||!!winner}/><div className="result-guide"><div className="result-strip">{resultNames.map(n=><span className={last===n?'active':''} key={n}><ResultIcon name={n}/><b>{n}</b></span>)}</div><div className="png-result"><strong>{result?.name||last||'준비'}</strong><p>{message}</p></div></div><div className="waiting-area"><div><b>빨강팀 대기</b>{pieces.filter(p=>p.team==='red'&&p.position===WAITING).map(p=><Pawn key={p.id} team="red" selectable={selectable.includes(p.id)} onClick={()=>choose(p.id)}/>)}</div><div><b>파랑팀 대기</b>{pieces.filter(p=>p.team==='blue'&&p.position===WAITING).map(p=><Pawn key={p.id} team="blue" selectable={selectable.includes(p.id)} onClick={()=>choose(p.id)}/>)}</div></div></aside>{showRules&&<Rules close={()=>setShowRules(false)}/>} {confirm&&<dialog open className="png-yut-modal"><div className="confirm-card"><h2>{confirm==='home'?'처음 화면으로 갈까요?':'새로 시작할까요?'}</h2><p>지금까지의 놀이는 사라져요.</p><div><Button variant="outline" onClick={()=>setConfirm(null)}>계속 놀기</Button><Button onClick={()=>confirm==='home'?onHome():reset()}>네, 시작해요</Button></div></div></dialog>}{winner&&<dialog open className="png-yut-modal"><div className="victory-card"><img src={pawnSrc(winner,2)} alt="업힌 윷말"/><h2>{names[winner]} 승리!</h2><p>축하해요! 두 개의 말이 모두 도착했어요!</p><div><Button onClick={reset}>같은 팀으로 다시 하기</Button><Button variant="outline" onClick={onBack}>팀 바꾸기</Button><Button variant="outline" onClick={onHome}>처음으로</Button></div></div></dialog>}<button className="game-home-guard" onClick={()=>setConfirm('home')} aria-label="게임을 끝내고 처음으로"/></section>}

export default function YutGame({home,soundOn,toggleSound}:{home:()=>void;soundOn:boolean;toggleSound:()=>void}){const[mode,setMode]=useState<Mode>('start');const[names,setNames]=useState<Record<Team,string>>({red:'빨강팀',blue:'파랑팀'});const guardedHome=()=>mode==='game'?document.querySelector<HTMLButtonElement>('.game-home-guard')?.click():home();return <main className="activity png-yut-app"><header className="topbar"><Button onClick={guardedHome} variant="outline" className="round-action"><span>처음으로</span></Button><div className="activity-title"><h1>함께하는 윷놀이</h1></div><Button onClick={toggleSound} variant="outline" className="round-action sound-only"><span>{soundOn?'소리 켬':'소리 끔'}</span></Button></header>{mode==='start'&&<section className="png-yut-start"><h2>윷을 던지고 나온 수만큼 말을 움직여요!</h2><div><button onClick={()=>setMode('practice')}><img src={`${asset}yut_flat.png`} alt="윷가락"/><b>윷놀이 연습</b><small>도·개·걸·윷·모·백도를 익혀요</small></button><button onClick={()=>setMode('names')}><img src={`${asset}traditional_yut_board.png`} alt="전통 정사각형 윷판"/><b>함께 윷놀이</b><small>빨강팀과 파랑팀이 함께 놀아요</small></button></div></section>}{mode==='practice'&&<Practice soundOn={soundOn} onBack={()=>setMode('start')}/>} {mode==='names'&&<section className="png-team-names"><Button variant="outline" onClick={()=>setMode('start')}>이전</Button><div><img src={`${asset}red_mal.png`} alt="빨강팀 말"/><img src={`${asset}blue_mal.png`} alt="파랑팀 말"/><h2>팀 이름을 정해요</h2><label>빨강 줄무늬 팀<Input value={names.red} maxLength={8} onChange={e=>setNames({...names,red:e.target.value||'빨강팀'})}/></label><label>파랑 꽃무늬 팀<Input value={names.blue} maxLength={8} onChange={e=>setNames({...names,blue:e.target.value||'파랑팀'})}/></label><Button onClick={()=>setMode('rules')}>게임 시작</Button></div></section>}{mode==='rules'&&<Rules start={()=>setMode('game')}/>} {mode==='game'&&<Game key={`${names.red}-${names.blue}`} soundOn={soundOn} names={names} onBack={()=>setMode('names')} onHome={home}/>}</main>}
