'use client';

import {useMemo,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {initialPieces,makeYutThrow,moveTarget,possibleRoutes,resolveMove,sequenceFor,type Face,type Piece,type Route,type Team,type ThrowResult} from './yut-logic';

type Mode='start'|'practice'|'names'|'game';
type BoardNode={id:number;x:number;y:number;label?:string};

const countWords=['','하나','둘','셋','넷','다섯'];
const nodes:BoardNode[]=[
  {id:0,x:50,y:92,label:'출발·도착'},{id:1,x:30,y:88},{id:2,x:16,y:76},{id:3,x:10,y:58},{id:4,x:14,y:38},{id:5,x:25,y:20},
  {id:6,x:50,y:9},{id:7,x:75,y:20},{id:8,x:86,y:38},{id:9,x:90,y:58},{id:10,x:84,y:76},{id:11,x:70,y:88},
  {id:13,x:38,y:34},{id:14,x:50,y:50,label:'가운데'},{id:15,x:62,y:66},{id:16,x:62,y:34},{id:17,x:38,y:66},
];
const nodeMap=new Map(nodes.map(node=>[node.id,node]));
function speak(text:string,on:boolean){if(!on||typeof window==='undefined'||!('speechSynthesis'in window))return;const synth=window.speechSynthesis;synth.cancel();let spoken=false;const say=()=>{if(spoken)return;spoken=true;const korean=synth.getVoices().filter(voice=>voice.lang.toLowerCase().replace('_','-').startsWith('ko'));const women=['Yuna','Flo','Sandy','Shelley','Grandma','SunHi','Heami','Seoyeon','Sora','Yu-ri','유나','소라','서연','희미','여성','Female'];const men=/Eddy|Grandpa|Reed|Rocko|InJoon|Joon|Minho|남성|Male/i;const preferred=women.map(name=>korean.find(voice=>voice.name.toLowerCase().includes(name.toLowerCase()))).find(Boolean)||korean.find(voice=>!men.test(voice.name))||korean[0];const utterance=new SpeechSynthesisUtterance(text.replaceAll('!','! '));utterance.lang='ko-KR';if(preferred)utterance.voice=preferred;utterance.rate=.86;utterance.pitch=1;utterance.volume=1;synth.speak(utterance)};if(synth.getVoices().some(voice=>voice.lang.toLowerCase().replace('_','-').startsWith('ko')))say();else{const ready=()=>{synth.removeEventListener('voiceschanged',ready);say()};synth.addEventListener('voiceschanged',ready);window.setTimeout(()=>{synth.removeEventListener('voiceschanged',ready);say()},1200)}}

function YutSticks({faces,rolling,onThrow,disabled}:{faces:Face[];rolling:boolean;onThrow:()=>void;disabled:boolean}){
  const startY=useRef<number|null>(null);
  return <section className="yut-throw-zone"><div className={`yut-sticks ${rolling?'rolling':''}`} onPointerDown={event=>{startY.current=event.clientY;event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={event=>{if(startY.current!==null&&startY.current-event.clientY>35&&!disabled)onThrow();startY.current=null}} aria-label="윷가락을 위로 밀어 던지기">{faces.map((face,index)=><span key={index} className={`yut-stick ${face}`}><i>{face==='flat'?'●':''}</i></span>)}</div><Button className="throw-yut" onClick={onThrow} disabled={disabled}>{rolling?'윷이 날아가요!':'윷 던지기'}</Button><small>버튼을 누르거나 윷가락을 위로 밀어요</small></section>
}

function Pawn({piece,count,selectable,onClick}:{piece:Piece;count:number;selectable:boolean;onClick:()=>void}){return <button className={`yut-pawn ${piece.team} ${selectable?'selectable':''}`} onClick={onClick} disabled={!selectable} aria-label={`${piece.team==='red'?'빨강':'파랑'}팀 말${count>1?` ${count}개 업기`:''}`}><i/>{count>1&&<b>{count}</b>}</button>}

function Board({pieces,selectableIds=[],targets=[],onPiece,onTarget}:{pieces:Piece[];selectableIds?:string[];targets?:{node:number;route:Route}[];onPiece:(id:string)=>void;onTarget:(node:number,route:Route)=>void}){
  const grouped=useMemo(()=>{const groups=new Map<string,Piece[]>();pieces.filter(piece=>piece.position>=0&&piece.position!==0).forEach(piece=>{const key=`${piece.team}-${piece.position}`;groups.set(key,[...(groups.get(key)||[]),piece])});return groups},[pieces]);
  return <div className="yut-board" role="group" aria-label="갈림길과 가운데 지름길이 있는 윷판"><svg viewBox="0 0 100 100" aria-hidden="true"><path d="M50 92 L30 88 L16 76 L10 58 L14 38 L25 20 L50 9 L75 20 L86 38 L90 58 L84 76 L70 88 Z"/><path d="M25 20 L38 34 L50 50 L62 66 L70 88 M75 20 L62 34 L50 50 L38 66 L50 92"/></svg>{nodes.map(node=>{const choices=targets.filter(target=>target.node===node.id);return <button key={node.id} className={`board-node ${choices.length?'target':''} ${node.id===0?'home-node':''}`} style={{left:`${node.x}%`,top:`${node.y}%`}} onClick={()=>choices[0]&&onTarget(node.id,choices[0].route)} disabled={!choices.length} aria-label={node.label||`${node.id}번 칸`}>{node.label&&<span>{node.label}</span>}</button>})}{[...grouped.values()].map(group=>{const piece=group[0];const point=nodeMap.get(piece.position)!;return <div className="pawn-place" key={`${piece.team}-${piece.position}`} style={{left:`${point.x}%`,top:`${point.y}%`}}><Pawn piece={piece} count={group.length} selectable={group.some(value=>selectableIds.includes(value.id))} onClick={()=>onPiece(group.find(value=>selectableIds.includes(value.id))?.id||piece.id)}/></div>})}</div>
}

function Rules({close}:{close:()=>void}){return <div className="yut-modal" role="dialog" aria-modal="true"><div className="yut-rules"><button className="yut-close" onClick={close} aria-label="규칙 닫기">×</button><h2>윷놀이 규칙</h2><div><span><b>도</b><i>1</i></span><span><b>개</b><i>2</i></span><span><b>걸</b><i>3</i></span><span><b>윷</b><i>4 + 한 번 더</i></span><span><b>모</b><i>5 + 한 번 더</i></span></div><p>윷을 던져요 → 움직일 말을 골라요 → 반짝이는 칸을 눌러요</p><p>같은 팀 말은 업고, 상대 말은 잡아요!</p></div></div>}

function Practice({soundOn,onBack}:{soundOn:boolean;onBack:()=>void}){
  const [faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[seen,setSeen]=useState<string[]>([]);const[position,setPosition]=useState(-1);const[moving,setMoving]=useState(false);const[message,setMessage]=useState('윷을 던져 도·개·걸·윷·모를 만나 보세요!');
  const practicePiece:Piece={id:'practice',team:'red',position,route:'outer'};
  const throwYut=()=>{if(rolling||moving||result)return;setRolling(true);window.setTimeout(()=>{const next=makeYutThrow();setFaces(next.faces);setResult(next);setSeen(current=>current.includes(next.name)?current:[...current,next.name]);setMessage(next.sentence);setRolling(false);speak(next.sentence,soundOn)},850)};
  const move=async()=>{if(!result||moving)return;setMoving(true);const sequence=sequenceFor(practicePiece,'outer');let last=position;for(let index=0;index<result.steps;index++){await new Promise(resolve=>window.setTimeout(resolve,380));last=sequence[Math.min(index,sequence.length-1)]??0;setPosition(last);speak(countWords[index+1],soundOn)}if(last===0){await new Promise(resolve=>window.setTimeout(resolve,400));setPosition(-1)}setResult(null);setMoving(false);setMessage(seen.length===5?'윷놀이 준비 완료!':'다시 윷을 던져 보세요!')};
  return <div className="yut-play"><div className="yut-subbar"><Button variant="outline" onClick={onBack}>← 이전</Button><h2>윷놀이 연습</h2><div className="seen-results">{['도','개','걸','윷','모'].map(name=><span key={name} className={seen.includes(name)?'seen':''}>{name}</span>)}</div></div><div className="yut-layout"><div className="yut-board-wrap"><Board pieces={position===0?[]:[practicePiece]} selectableIds={result&&!moving?['practice']:[]} onPiece={move} targets={[]} onTarget={()=>{}}/>{position<0&&<button className={`start-pawn ${result?'selectable':''}`} onClick={move} disabled={!result||moving}><span className="yut-pawn red"><i/></span>연습 말</button>}</div><aside><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={rolling||moving||!!result}/><div className="yut-result"><strong>{result?.name||'준비'}</strong><p>{message}</p></div>{seen.length===5&&<div className="practice-badge">윷놀이 준비 완료!</div>}</aside></div></div>
}

function TeamPanel({team,name,pieces,active}:{team:Team;name:string;pieces:Piece[];active:boolean}){const mine=pieces.filter(piece=>piece.team===team);return <article className={`team-panel ${team} ${active?'active':''}`}><h3><i/>{name}</h3><div><span>출발 전 <b>{mine.filter(piece=>piece.position<0).length}</b></span><span>윷판 위 <b>{mine.filter(piece=>piece.position>0).length}</b></span><span>도착 <b>{mine.filter(piece=>piece.position===0).length}</b></span></div></article>}

function Game({soundOn,names,onBack,onHome}:{soundOn:boolean;names:Record<Team,string>;onBack:()=>void;onHome:()=>void}){
  const[pieces,setPieces]=useState<Piece[]>(initialPieces);const[turn,setTurn]=useState<Team>('red');const[faces,setFaces]=useState<Face[]>(['round','flat','round','flat']);const[rolling,setRolling]=useState(false);const[moving,setMoving]=useState(false);const[result,setResult]=useState<ThrowResult|null>(null);const[lastResult,setLastResult]=useState('없음');const[selected,setSelected]=useState<string|null>(null);const[targets,setTargets]=useState<{node:number;route:Route}[]>([]);const[message,setMessage]=useState(`${names.red} 차례예요. 윷을 던져요!`);const[extra,setExtra]=useState(false);const[bonusTurn,setBonusTurn]=useState(false);const[winner,setWinner]=useState<Team|null>(null);const[showRules,setShowRules]=useState(false);const[confirm,setConfirm]=useState<'restart'|'home'|null>(null);
  const piecesRef=useRef<Piece[]>(pieces);
  const selectable=useMemo(()=>result&&!moving?pieces.filter(piece=>piece.team===turn&&piece.position!==0).map(piece=>piece.id):[],[pieces,result,moving,turn]);
  const throwYut=()=>{if(rolling||moving||result||winner)return;setRolling(true);setBonusTurn(false);setSelected(null);setTargets([]);window.setTimeout(()=>{const next=makeYutThrow();setFaces(next.faces);setResult(next);setLastResult(next.name);setExtra(next.extra);setRolling(false);setMessage(next.sentence+' 움직일 말을 골라요.');speak(next.sentence,soundOn)},850)};
  const choosePiece=(id:string)=>{if(!result||moving)return;const piece=pieces.find(value=>value.id===id);if(!piece||piece.team!==turn||piece.position===0)return;const choices=possibleRoutes(piece).map(route=>({route,node:moveTarget(piece,result.steps,route)}));setSelected(id);setTargets(choices);setMessage(choices.length>1?'바깥길과 가운데 지름길 중에서 골라요.':'반짝이는 도착 칸을 눌러요.')};
  const movePiece=async(_node:number,route:Route)=>{if(!result||!selected||moving)return;const resolution=resolveMove(piecesRef.current,turn,selected,result.steps,route,extra);setMoving(true);setTargets([]);for(let index=0;index<resolution.path.length;index++){await new Promise(resolve=>window.setTimeout(resolve,360));const next=resolution.path[index];setPieces(current=>{const updated=current.map(piece=>resolution.movingIds.includes(piece.id)?{...piece,position:next,route}:piece);piecesRef.current=updated;return updated});speak(countWords[index+1],soundOn)}piecesRef.current=resolution.finalPieces;setPieces(resolution.finalPieces);setMoving(false);setResult(null);setSelected(null);if(resolution.won){setWinner(turn);setMessage('축하해요! 두 개의 말이 모두 도착했어요!');speak(`${names[turn]} 승리! 축하해요! 두 개의 말이 모두 도착했어요!`,soundOn);return}setBonusTurn(resolution.extra);if(resolution.caughtIds.length){setMessage('상대 말을 잡았어요! 한 번 더 던져요.');speak('상대 말을 잡았어요! 한 번 더 던져요.',soundOn)}else if(resolution.extra){setMessage('한 번 더! 다시 윷을 던져요.')}else{const nextTeam=turn==='red'?'blue':'red';setTurn(nextTeam);setMessage(`${names[nextTeam]} 차례예요. 윷을 던져요!`)}setExtra(false)};
  const reset=()=>{const fresh=initialPieces();piecesRef.current=fresh;setPieces(fresh);setTurn('red');setFaces(['round','flat','round','flat']);setRolling(false);setMoving(false);setResult(null);setLastResult('없음');setSelected(null);setTargets([]);setExtra(false);setBonusTurn(false);setWinner(null);setMessage(`${names.red} 차례예요. 윷을 던져요!`);setConfirm(null)};
  return <div className="yut-play"><div className="game-info"><TeamPanel team="red" name={names.red} pieces={pieces} active={turn==='red'}/><div className="turn-card"><span>현재 차례</span><strong className={turn}>{names[turn]}</strong><small>직전 결과: {lastResult}</small>{(extra||bonusTurn)&&<b>한 번 더!</b>}</div><TeamPanel team="blue" name={names.blue} pieces={pieces} active={turn==='blue'}/></div><div className="yut-game-actions"><Button variant="outline" onClick={()=>{setTargets([]);selected&&choosePiece(selected)}} disabled={!result}>힌트</Button><Button variant="outline" onClick={()=>setShowRules(true)}>규칙 보기</Button><Button variant="outline" onClick={()=>setConfirm('restart')}>처음부터</Button></div><div className="yut-layout"><div className="yut-board-wrap"><Board pieces={pieces} selectableIds={selectable} targets={targets} onPiece={choosePiece} onTarget={movePiece}/><div className="start-pieces">{pieces.filter(piece=>piece.team===turn&&piece.position<0).map(piece=><Pawn key={piece.id} piece={piece} count={1} selectable={selectable.includes(piece.id)} onClick={()=>choosePiece(piece.id)}/>)}</div><div className="finish-pieces">{pieces.filter(piece=>piece.position===0).map(piece=><Pawn key={piece.id} piece={piece} count={1} selectable={false} onClick={()=>{}}/>)}</div></div><aside><YutSticks faces={faces} rolling={rolling} onThrow={throwYut} disabled={rolling||moving||!!result||!!winner}/><div className="yut-result"><strong>{result?.name||'준비'}</strong><p>{message}</p></div></aside></div>{showRules&&<Rules close={()=>setShowRules(false)}/>} {confirm&&<div className="yut-modal" role="dialog" aria-modal="true"><div className="confirm-card"><h2>{confirm==='home'?'처음 화면으로 갈까요?':'새로 시작할까요?'}</h2><p>지금까지의 놀이는 사라져요.</p><div><Button variant="outline" onClick={()=>setConfirm(null)}>계속 놀기</Button><Button onClick={()=>confirm==='home'?onHome():reset()}>네, 시작해요</Button></div></div></div>}{winner&&<div className="yut-modal victory" role="dialog" aria-modal="true"><div className="victory-card"><div className={`winner-pawn ${winner}`}><i/></div><h2>{names[winner]} 승리!</h2><p>축하해요! 두 개의 말이 모두 도착했어요!</p><div><Button onClick={reset}>같은 팀으로 다시 하기</Button><Button variant="outline" onClick={onBack}>팀 바꾸기</Button><Button variant="outline" onClick={onHome}>처음으로</Button></div></div></div>}<button className="game-home-guard" onClick={()=>setConfirm('home')} aria-label="게임을 끝내고 처음으로"/></div>
}

export default function YutGame({home,soundOn,toggleSound}:{home:()=>void;soundOn:boolean;toggleSound:()=>void}){
  const[mode,setMode]=useState<Mode>('start');const[names,setNames]=useState<Record<Team,string>>({red:'빨강팀',blue:'파랑팀'});
  const guardedHome=()=>{if(mode==='game'){document.querySelector<HTMLButtonElement>('.game-home-guard')?.click()}else home()};
  return <main className="activity activity-yut"><header className="topbar"><Button onClick={guardedHome} variant="outline" className="round-action"><span>처음으로</span></Button><div className="activity-title"><h1>함께하는 윷놀이</h1></div><Button onClick={toggleSound} variant="outline" className="round-action sound-only"><span>{soundOn?'소리 켬':'소리 끔'}</span></Button></header>{mode==='start'&&<section className="yut-start"><div><h2>윷을 던지고 나온 수만큼 말을 움직여요!</h2><p>어떤 놀이를 해 볼까요?</p></div><div className="yut-mode-grid"><button onClick={()=>setMode('practice')}><img src="/yutnori-menu.png" alt="윷가락과 윷판"/><strong>윷놀이 연습</strong><span>도·개·걸·윷·모를 익혀요</span></button><button onClick={()=>setMode('names')}><img src="/yutnori-menu.png" alt="빨강팀과 파랑팀 윷놀이"/><strong>함께 윷놀이</strong><span>두 팀이 말을 움직여요</span></button></div></section>}{mode==='practice'&&<Practice soundOn={soundOn} onBack={()=>setMode('start')}/>} {mode==='names'&&<section className="team-names"><Button variant="outline" onClick={()=>setMode('start')}>← 이전</Button><div><img src="/yutnori-menu.png" alt="함께하는 윷놀이"/><h2>팀 이름을 정해요</h2><label>빨강 문양 팀<Input value={names.red} maxLength={8} onChange={event=>setNames({...names,red:event.target.value||'빨강팀'})}/></label><label>파랑 꽃문양 팀<Input value={names.blue} maxLength={8} onChange={event=>setNames({...names,blue:event.target.value||'파랑팀'})}/></label><Button onClick={()=>setMode('game')}>게임 시작!</Button></div></section>}{mode==='game'&&<Game key={`${names.red}-${names.blue}`} soundOn={soundOn} names={names} onBack={()=>setMode('names')} onHome={home}/>}</main>
}
